spring.application.name=LSHOE Store
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/lshoe_store}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:120505}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.thymeleaf.cache=false
server.port=8081
ai.service.url=${AI_SERVICE_URL:http://localhost:8001}
