-- Current PostgreSQL schema plus idempotent upgrades for databases created by older releases.

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    phone VARCHAR(20),
    address VARCHAR(500),
    session_version INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    name VARCHAR(160) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    description VARCHAR(2000),
    price NUMERIC(15, 2) NOT NULL,
    old_price NUMERIC(15, 2),
    image_url VARCHAR(1000),
    size_text VARCHAR(160),
    stock INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'CHO_XAC_NHAN',
    total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    checkout_token VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(160),
    product_brand VARCHAR(100),
    quantity INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    selected_size VARCHAR(160)
);

CREATE TABLE IF NOT EXISTS saved_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected_size VARCHAR(160)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP
);

-- Columns introduced after the first project versions.
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version INTEGER DEFAULT 0;
ALTER TABLE product ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE product ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE product ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_token VARCHAR(64);
ALTER TABLE saved_cart_items ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE saved_cart_items ADD COLUMN IF NOT EXISTS selected_size VARCHAR(160);
ALTER TABLE order_item ADD COLUMN IF NOT EXISTS product_name VARCHAR(160);
ALTER TABLE order_item ADD COLUMN IF NOT EXISTS product_brand VARCHAR(100);
ALTER TABLE order_item ADD COLUMN IF NOT EXISTS selected_size VARCHAR(160);

UPDATE users SET session_version = 0 WHERE session_version IS NULL;
UPDATE product SET version = 0 WHERE version IS NULL;
UPDATE saved_cart_items SET version = 0 WHERE version IS NULL;
UPDATE product SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE product SET updated_at = COALESCE(created_at, CURRENT_TIMESTAMP) WHERE updated_at IS NULL;
UPDATE orders SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE orders SET status = 'CHO_XAC_NHAN' WHERE status IS NULL OR BTRIM(status) = '';
UPDATE orders SET total = 0 WHERE total IS NULL OR total < 0;
UPDATE orders SET completed_at = created_at WHERE status = 'HOAN_THANH' AND completed_at IS NULL;
UPDATE product SET stock = 0 WHERE stock IS NULL OR stock < 0;
UPDATE product SET active = TRUE WHERE active IS NULL;
UPDATE saved_cart_items SET quantity = 1 WHERE quantity IS NULL OR quantity <= 0;
UPDATE product SET old_price = NULL
WHERE old_price IS NOT NULL AND (old_price <= 0 OR old_price < price);

UPDATE order_item oi
SET product_name = COALESCE(NULLIF(BTRIM(oi.product_name), ''),
                            NULLIF(BTRIM(p.name), ''), 'Sản phẩm')
FROM product p
WHERE oi.product_id = p.id
  AND (oi.product_name IS NULL OR BTRIM(oi.product_name) = '');

UPDATE order_item oi
SET product_brand = COALESCE(NULLIF(BTRIM(oi.product_brand), ''),
                             NULLIF(BTRIM(p.brand), ''), 'Không rõ')
FROM product p
WHERE oi.product_id = p.id
  AND (oi.product_brand IS NULL OR BTRIM(oi.product_brand) = '');

UPDATE order_item SET product_name = BTRIM(product_name)
WHERE product_name IS NOT NULL AND product_name <> BTRIM(product_name);
UPDATE order_item SET product_brand = BTRIM(product_brand)
WHERE product_brand IS NOT NULL AND product_brand <> BTRIM(product_brand);

UPDATE saved_cart_items s
SET selected_size = COALESCE((
    SELECT BTRIM(size_value.value)
    FROM REGEXP_SPLIT_TO_TABLE(
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
            COALESCE(p.size_text, ''), ';', ','), '/', ','), '|', ','), CHR(10), ','), CHR(13), ','),
        ','
    ) AS size_value(value)
    WHERE BTRIM(size_value.value) <> ''
    LIMIT 1
), 'Không áp dụng')
FROM product p
WHERE s.product_id = p.id
  AND (s.selected_size IS NULL OR BTRIM(s.selected_size) = '');

UPDATE order_item oi
SET selected_size = COALESCE((
    SELECT BTRIM(size_value.value)
    FROM REGEXP_SPLIT_TO_TABLE(
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
            COALESCE(p.size_text, ''), ';', ','), '/', ','), '|', ','), CHR(10), ','), CHR(13), ','),
        ','
    ) AS size_value(value)
    WHERE BTRIM(size_value.value) <> ''
    LIMIT 1
), 'Không áp dụng')
FROM product p
WHERE oi.product_id = p.id
  AND (oi.selected_size IS NULL OR BTRIM(oi.selected_size) = '');

UPDATE saved_cart_items SET selected_size = BTRIM(selected_size)
WHERE selected_size IS NOT NULL AND selected_size <> BTRIM(selected_size);
UPDATE order_item SET selected_size = BTRIM(selected_size)
WHERE selected_size IS NOT NULL AND selected_size <> BTRIM(selected_size);

-- Remove the old uniqueness rule that allowed only one row per product, regardless of size.
DO $$
DECLARE object_name TEXT;
BEGIN
    FOR object_name IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace ns ON ns.oid = rel.relnamespace
        WHERE ns.nspname = current_schema()
          AND rel.relname = 'saved_cart_items'
          AND con.contype = 'u'
          AND (
              REPLACE(REPLACE(pg_get_constraintdef(con.oid), ' ', ''), CHR(34), '') ILIKE '%(user_id,product_id)%'
              OR REPLACE(REPLACE(pg_get_constraintdef(con.oid), ' ', ''), CHR(34), '') ILIKE '%(product_id,user_id)%'
          )
          AND pg_get_constraintdef(con.oid) NOT ILIKE '%selected_size%'
    LOOP
        EXECUTE format('ALTER TABLE saved_cart_items DROP CONSTRAINT IF EXISTS %I', object_name);
    END LOOP;

    FOR object_name IN
        SELECT indexname
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename = 'saved_cart_items'
          AND indexdef ILIKE 'CREATE UNIQUE INDEX%'
          AND (
              REPLACE(REPLACE(indexdef, ' ', ''), CHR(34), '') ILIKE '%(user_id,product_id)%'
              OR REPLACE(REPLACE(indexdef, ' ', ''), CHR(34), '') ILIKE '%(product_id,user_id)%'
          )
          AND indexdef NOT ILIKE '%selected_size%'
    LOOP
        EXECUTE format('DROP INDEX IF EXISTS %I', object_name);
    END LOOP;
END $$;

UPDATE saved_cart_items keeper
SET quantity = LEAST(merged.total_quantity, 2147483647)::INTEGER
FROM (
    SELECT MIN(id) AS keep_id,
           SUM(GREATEST(quantity, 1)::BIGINT) AS total_quantity
    FROM saved_cart_items
    GROUP BY user_id, product_id, LOWER(BTRIM(selected_size))
    HAVING COUNT(*) > 1
) merged
WHERE keeper.id = merged.keep_id;

DELETE FROM saved_cart_items duplicate
USING saved_cart_items keeper
WHERE duplicate.user_id = keeper.user_id
  AND duplicate.product_id = keeper.product_id
  AND LOWER(BTRIM(duplicate.selected_size)) = LOWER(BTRIM(keeper.selected_size))
  AND duplicate.id > keeper.id;

ALTER TABLE order_item ALTER COLUMN product_name SET NOT NULL;
ALTER TABLE order_item ALTER COLUMN product_brand SET NOT NULL;
ALTER TABLE order_item ALTER COLUMN selected_size SET NOT NULL;
ALTER TABLE saved_cart_items ALTER COLUMN selected_size SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_category_name ON category(name);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS uk_orders_checkout_token ON orders(checkout_token);
CREATE UNIQUE INDEX IF NOT EXISTS uk_password_reset_token_hash ON password_reset_tokens(token_hash);
DROP INDEX IF EXISTS uk_saved_cart_user_product_size;
CREATE UNIQUE INDEX uk_saved_cart_user_product_size
    ON saved_cart_items(user_id, product_id, LOWER(BTRIM(selected_size)));

CREATE INDEX IF NOT EXISTS idx_product_active ON product(active);
CREATE INDEX IF NOT EXISTS idx_product_category ON product(category_id);
CREATE INDEX IF NOT EXISTS idx_order_user_created ON orders(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_order_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_saved_cart_user ON saved_cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_cart_product ON saved_cart_items(product_id);
CREATE INDEX IF NOT EXISTS idx_reset_token_hash ON password_reset_tokens(token_hash);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_category') THEN
        ALTER TABLE product ADD CONSTRAINT fk_product_category
            FOREIGN KEY (category_id) REFERENCES category(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_user') THEN
        ALTER TABLE orders ADD CONSTRAINT fk_orders_user
            FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_item_order') THEN
        ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order
            FOREIGN KEY (order_id) REFERENCES orders(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_item_product') THEN
        ALTER TABLE order_item ADD CONSTRAINT fk_order_item_product
            FOREIGN KEY (product_id) REFERENCES product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_saved_cart_user') THEN
        ALTER TABLE saved_cart_items ADD CONSTRAINT fk_saved_cart_user
            FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_saved_cart_product') THEN
        ALTER TABLE saved_cart_items ADD CONSTRAINT fk_saved_cart_product
            FOREIGN KEY (product_id) REFERENCES product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reset_token_user') THEN
        ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_reset_token_user
            FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_product_stock_nonnegative') THEN
        ALTER TABLE product ADD CONSTRAINT chk_product_stock_nonnegative CHECK (stock >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_product_price_positive') THEN
        ALTER TABLE product ADD CONSTRAINT chk_product_price_positive CHECK (price > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_product_old_price_valid') THEN
        ALTER TABLE product ADD CONSTRAINT chk_product_old_price_valid CHECK (old_price IS NULL OR old_price >= price);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_saved_cart_quantity_positive') THEN
        ALTER TABLE saved_cart_items ADD CONSTRAINT chk_saved_cart_quantity_positive CHECK (quantity > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_saved_cart_selected_size_nonblank') THEN
        ALTER TABLE saved_cart_items ADD CONSTRAINT chk_saved_cart_selected_size_nonblank CHECK (BTRIM(selected_size) <> '');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_item_quantity_positive') THEN
        ALTER TABLE order_item ADD CONSTRAINT chk_order_item_quantity_positive CHECK (quantity > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_item_selected_size_nonblank') THEN
        ALTER TABLE order_item ADD CONSTRAINT chk_order_item_selected_size_nonblank CHECK (BTRIM(selected_size) <> '');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_item_price_nonnegative') THEN
        ALTER TABLE order_item ADD CONSTRAINT chk_order_item_price_nonnegative CHECK (price >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_item_product_name_nonblank') THEN
        ALTER TABLE order_item ADD CONSTRAINT chk_order_item_product_name_nonblank CHECK (BTRIM(product_name) <> '');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_item_product_brand_nonblank') THEN
        ALTER TABLE order_item ADD CONSTRAINT chk_order_item_product_brand_nonblank CHECK (BTRIM(product_brand) <> '');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_order_total_nonnegative') THEN
        ALTER TABLE orders ADD CONSTRAINT chk_order_total_nonnegative CHECK (total >= 0);
    END IF;
END $$;
