-- LSHOE final PostgreSQL schema.
-- This squashed migration replaces the former V1, V2, V4, V5, V6, V7 and V8 files.
-- It is intended only for a newly created or fully reset database.

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    phone VARCHAR(20),
    address VARCHAR(500),
    session_version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(160) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    description VARCHAR(2000),
    price NUMERIC(15, 2) NOT NULL,
    old_price NUMERIC(15, 2),
    image_url VARCHAR(1000),
    size_text VARCHAR(2000),
    stock INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT chk_product_stock_nonnegative CHECK (stock >= 0),
    CONSTRAINT chk_product_price_positive CHECK (price > 0),
    CONSTRAINT chk_product_old_price_valid
        CHECK (old_price IS NULL OR old_price >= price)
);

CREATE TABLE product_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    product_id BIGINT NOT NULL,
    size VARCHAR(160) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_product_variant_product
        FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT chk_product_variant_size_nonblank CHECK (BTRIM(size) <> ''),
    CONSTRAINT chk_product_variant_stock_nonnegative CHECK (stock >= 0)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'CHO_XAC_NHAN',
    total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    checkout_token VARCHAR(64),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_order_total_nonnegative CHECK (total >= 0)
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(160) NOT NULL,
    product_brand VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    selected_size VARCHAR(160) NOT NULL,
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT chk_order_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_order_item_selected_size_nonblank CHECK (BTRIM(selected_size) <> ''),
    CONSTRAINT chk_order_item_price_nonnegative CHECK (price >= 0),
    CONSTRAINT chk_order_item_product_name_nonblank CHECK (BTRIM(product_name) <> ''),
    CONSTRAINT chk_order_item_product_brand_nonblank CHECK (BTRIM(product_brand) <> '')
);

CREATE TABLE saved_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected_size VARCHAR(160) NOT NULL,
    CONSTRAINT fk_saved_cart_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_saved_cart_product
        FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT chk_saved_cart_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_saved_cart_selected_size_nonblank CHECK (BTRIM(selected_size) <> '')
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP,
    CONSTRAINT fk_reset_token_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE pending_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_token VARCHAR(64) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(500),
    verification_code_hash VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_pending_registration_attempts CHECK (failed_attempts >= 0)
);

CREATE TABLE request_rate_limits (
    rate_key VARCHAR(64) PRIMARY KEY,
    window_started_at TIMESTAMPTZ NOT NULL,
    window_seconds INTEGER NOT NULL,
    request_count INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_rate_limit_window_seconds CHECK (window_seconds > 0),
    CONSTRAINT chk_rate_limit_request_count CHECK (request_count > 0)
);

CREATE UNIQUE INDEX uk_category_name
    ON category(name);
CREATE UNIQUE INDEX uk_users_email_normalized
    ON users(LOWER(BTRIM(email)));
CREATE UNIQUE INDEX uk_product_variant_product_size
    ON product_variant(product_id, LOWER(BTRIM(size)));
CREATE UNIQUE INDEX uk_orders_checkout_token
    ON orders(checkout_token);
CREATE UNIQUE INDEX uk_saved_cart_user_product_size
    ON saved_cart_items(user_id, product_id, LOWER(BTRIM(selected_size)));
CREATE UNIQUE INDEX uk_password_reset_token_hash
    ON password_reset_tokens(token_hash);
CREATE UNIQUE INDEX uk_pending_registration_token
    ON pending_registrations(registration_token);

CREATE INDEX idx_product_active
    ON product(active);
CREATE INDEX idx_product_category
    ON product(category_id);
CREATE INDEX idx_product_variant_product
    ON product_variant(product_id);
CREATE INDEX idx_product_variant_enabled_stock
    ON product_variant(enabled, stock);
CREATE INDEX idx_order_user_created
    ON orders(user_id, created_at);
CREATE INDEX idx_order_status
    ON orders(status);
CREATE INDEX idx_saved_cart_user
    ON saved_cart_items(user_id);
CREATE INDEX idx_saved_cart_product
    ON saved_cart_items(product_id);
CREATE INDEX idx_reset_token_hash
    ON password_reset_tokens(token_hash);
CREATE INDEX idx_pending_registration_email
    ON pending_registrations(email);
CREATE INDEX idx_pending_registration_email_normalized
    ON pending_registrations(LOWER(BTRIM(email)));
CREATE INDEX idx_pending_registration_expires
    ON pending_registrations(expires_at);
CREATE INDEX idx_request_rate_limits_expires_at
    ON request_rate_limits(expires_at);
